### ISSUE TITLE
How i can set Position of menu?

### ISSUE THREAD

**Issue by amirch123** [epv44/EVTopTabBar#1]
Hello
I want to move my menu to the middle of the scree, and put a label on top of it.
plz help

**Comment by epv44** [comment]
Hi, this plugin is intended to be used as a top tab bar (not positioned in the middle of the screen).
Because of that I'm going to close this issue.

However, you could attempt to implement the `setupConstraints` function in the `EVTabBar` Protocol.  That may allow you to move the `topTabBar` to a different place on the screen.
